[profile.default]
solc = "0.8.16"
bytecode_hash = "none"
runs = 1024
fuzz_max_global_rejects = 1000
optimizer_runs = 1000
via_ir = false

[profile.intense.fuzz]
runs = 32768

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_MAINNET_KEY}"
goerli = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_GOERLI_KEY}"
